 %%%% Image Size %%%% ↓
inputsize=[224 224 1];

%%%% Model File %%%% ↓
unet= model(inputsize,0);

%%%% Hyperparameter Settings %%%% % ↓
options = trainingOptions('adam', ... 
'MiniBatchSize',64, ...
'Shuffle','every-epoch', ... 
'ValidationData',varSet, ...
'MaxEpochs',150, ...
'Plots','training-progress', ... 
'InitialLearnRate',0.0005, ...
'LearnRateSchedule','piecewise', ... 
'LearnRateDropFactor',0.90, ...
'LearnRateDropPeriod', 15, ...
'L2Regularization',0.002, ...
'Verbose',true, ...
'VerboseFrequency', 195, ... 
'ValidationFrequency',195, ...
'ExecutionEnvironment','gpu');

%%%% Details of the training process %%%%
[net,netinfo]=trainNetwork(trainSet,'labelimg',unet,options);